### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sajati** [kmille36/XiaomiMiMix2s-Windows-ARM#1]
Bro i followed your guide without succeess, now my partition is completely messed and cannot flash any firmware, would you mind share your original partition table with parted ? if so please change the unit in "s" / sector instead of "MiB"

Here's myu forum post https://forum.renegade-project.org/t/help-needed-breaks-my-mi-mix-2s-partition/3021

**Comment by kmille36** [comment]
Hi, contact me over:
1. fb: https://fb.com/thuong.hai.581
2. discord: thuonghai2711#7681

Waiting for your reply ...

**Comment by kmille36** [comment]
I want to know exactly what you did, send me which command you use (cause your problem), and more screenshot (if you have).
